default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: real-ratings_development
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>

test:
  <<: *default
  database: real-ratings_test
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
