version: '3.8'

services:
  db:
    image: postgres:15
    container_name: real-ratings-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c 'max_connections=500'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    ports:
      - "${POSTGRES_PORT}:5432"

  real-ratings:
    build:
      context: .
      args:
        RAILS_ENV: ${RAILS_ENV}
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]
    environment:
      - RAILS_ENV=${RAILS_ENV:-production}  # Default to production if not set
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    volumes:
      - .:/rails
      - app-storage:/rails/storage
    depends_on:
      - db
    ports:
      - "3000:3000"
    # Remove or keep env_file based on your local vs production setup
    # env_file:
    #   - .env

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data: {}
  app-storage: {}

