name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
  workflow_dispatch: # Allows manual triggering

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: source

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.5

      - name: Install Ruby dependencies
        run: |
          gem install bundler
          bundle update
          bundle install --jobs 4 --retry 3

      - name: Run Rubocop
        run: bundle exec rubocop

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: source

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_DB: real-ratings_test
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.5

      - name: Install dependencies
        run: |
          gem install bundler
          bundle update
          bundle install --jobs 4 --retry 3

      - name: Set up database
        run: |
          bin/rails db:drop:_unsafe
          bin/rails db:create
          bin/rails db:migrate
          bin/rails db:seed

        env:
          RAILS_ENV: test
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432

      - name: Run tests
        run: |
          bundle exec rspec .

  deploy:
    needs: [test, static_analysis]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: source

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
          git push heroku main

      - name: Run database migrations
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku run rails db:migrate --app ${{ secrets.HEROKU_APP_NAME }}

      - name: Seed database
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku run rails db:seed --app ${{ secrets.HEROKU_APP_NAME }}
